<h5><?php _lang('ads-location')?></h5>
<form action="" method="post">

    <div class="form-group row">
        <label class="label col-sm-12"><?php _lang('top-location')?></label>
        <textarea style="height: 200px" name="val[top_ads]" class="form-control col-sm-12"><?php echo config('top_ads', '')?></textarea>
    </div>

    <div class="form-group row">
        <label class="label col-sm-12"><?php _lang('side-location')?></label>
        <textarea style="height: 200px" name="val[side_ads]" class="form-control col-sm-12"><?php echo config('side_ads', '')?></textarea>
    </div>

    <div  style="padding: 10px; text-align: center">
        <button class="btn btn-primary btn-sm"><?php _lang('save')?></button>
    </div>
</form>