<h5><?php _lang('appearance')?></h5>
<hr/>
<form action="" method="post">
    <div class="form-group row">
        <label class="col-sm-4"><?php _lang('theme')?></label>
        <div class="col-sm-8">
            <select name="val[theme]" class=" form-control-sm">
                <?php foreach(get_theme_list() as $theme):?>
                    <option <?php echo (config('theme','default') == $theme) ?'selected' : null?> value="<?php echo $theme?>"><?php echo ucwords($theme)?></option>
                <?php endforeach?>
            </select>
            <button class="btn btn-primary btn-sm"><?php _lang('save')?></button>
        </div>
    </div>
</form>
<hr/>
<h5><?php _lang('current-theme-options')?></h5>
<form action="" method="post">

    <?php foreach(get_theme_options() as $id => $option):?>
        <div class="form-group row" style="border-bottom: solid 1px #F5F5F5;padding-bottom:20px;">
            <label for="example-text-input" class=" col-form-label col-sm-4"><?php  _lang($option['title'])?></label>
            <div class="col-sm-8">

                <?php if($option['type']== 'text'):?>
                    <input class="form-control" type="text" name="val[<?php echo $id?>]" value="<?php echo config($id,$option['value'])?>">
                <?php elseif($option['type']== 'number'):?>
                    <input class="form-control" type="number" name="val[<?php echo $id?>]" value="<?php echo config($id,$option['value'])?>">
                <?php elseif($option['type']== 'color'):?>

                    <div class="input-group mb-2 mr-sm-2 mb-sm-0 color-picker">
                        <div class="input-group-addon holder" style="background-color: <?php echo config($id,$option['value'])?>"></div>
                        <input name="val[<?php echo $id?>]" type="text" class="form-control" value="<?php echo config($id,$option['value'])?>"  >
                    </div>
                <?php elseif($option['type']== 'textarea'):?>
                    <textarea class="form-control" type="text" name="val[<?php echo $id?>]" ><?php echo config($id,$option['value'])?></textarea>
                <?php elseif($option['type']== 'selection'):?>
                    <select style="width:100%" class="custom-select" name="val[<?php echo $id?>]">
                        <?php foreach($option['data'] as $d => $dName):?>
                            <option value="<?php echo $d?>" <?php echo ($d == config($id,$option['value'])) ? 'selected' : null?>><?php _lang($dName)?></option>
                        <?php endforeach?>
                    </select>
                <?php elseif($option['type']== 'img-upload'):?>
                    <input type="hidden" name="img[<?php echo $id?>]" value="<?php echo config($id,$option['value'])?>"/>
                    <?php $display = (isset($option['display'])) ? $option['display']: array(100, 50)?>
                    <?php if(config($id,$option['value'])):?>
                        <img style="display:block;margin-bottom:10px;width:<?php echo $display[0]?>px;height:<?php echo $display[1]?>px" src="<?php echo url(config($id,$option['value']))?>"/>
                    <?php endif?>
                    <input type="file" id="<?php echo $id?>" name="<?php echo $id?>" class="form-control">
                <?php elseif($option['type']== 'file-upload'):?>
                    <input type="hidden" name="file[<?php echo $id?>]" value="<?php echo config($id,$option['value'])?>"/>
                    <input style="width: 100%;" type="file" id="<?php echo $id?>" name="<?php echo $id?>" class="form-control">
                <?php elseif($option['type']== 'boolean'):?>
                    <div class="custom-controls-stacked">
                        <label class="custom-control custom-radio">
                            <input <?php echo (1 == config($id,$option['value'])) ? 'checked' : null?>  name="val[<?php echo $id?>]" value="1" type="radio" class="custom-control-input">
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description"><?php _lang('Admin::yes')?></span>
                        </label>
                        <label class="custom-control custom-radio">
                            <input <?php echo (0 == config($id,$option['value'])) ? 'checked' : null?>  name="val[<?php echo $id?>]" value="0" type="radio" class="custom-control-input">
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description"><?php _lang('Admin::no')?></span>
                        </label>
                    </div>
                <?php endif?>
                <?php if(isset($option['description']) and $option['description']):?>
                    <small class="form-text text-muted"><?php _lang($option['description'])?></small>
                <?php endif?>
            </div>
        </div>
    <?php endforeach?>

    <hr/>
    <button class="btn btn-primary btn-sm"><?php _lang('save')?></button>
</form>