<h5><?php _lang('users-management')?></h5>
<table class="table" id="dataTable">
    <thead>
        <tr>
            <th>ID</th>
            <th><?php _lang('username')?></th>
            <th><?php _lang('full-name')?></th>
            <th><?php _lang('email-address')?></th>
            <th><?php _lang('last-active')?></th>
            <th><?php _lang('active')?></th>
            <th><?php _lang('options')?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach(admin_get_user_lists() as $user):?>
            <tr>
                <td><?php echo $user['id']?></td>
                <td>
                    <a href="<?php echo profile_link($user)?>">
                        <img src="<?php echo get_avatar(75, $user)?>" style="width: 20px;height:20px;border-radius:100px"/> <?php echo $user['username']?>
                    </a>
                </td>
                <td><?php echo $user['full_name']?></td>
                <td><?php echo $user['email']?></td>
                <td><?php echo format_time($user['last_active'])?></td>
                <td><span class="badge badge-info"><?php echo ($user['active']) ? lang('yes') : lang('no')?></span></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-secondary ajax-link" href="<?php echo url('admin/user/edit?id='.$user['id'])?>"><i class="icons icon-pencil"></i></a>
                        <a class="btn btn-sm btn-secondary " href="<?php echo url('admin/user/edit?type=delete&id='.$user['id'])?>"><i class="icons icon-close"></i></a>
                    </div>

                </td>
            </tr>
        <?php endforeach?>
    </tbody>
</table>