<form action="" method="post" enctype="multipart/form-data">
    <?php if($error):?>
        <div class="alert alert-danger"><?php echo $error?></div>
    <?php endif?>
    <?php if($message):?>
        <div class="alert alert-success"><?php echo $message?></div>
    <?php endif?>

    <div class="form-group row">
        <label class="label col-sm-4"><?php _lang('old-password')?></label>
        <input type="password" class="form-control col-sm-6" name="old" />
    </div>

    <div class="form-group row">
        <label class="label col-sm-4"><?php _lang('new-password')?></label>
        <input type="password" class="form-control col-sm-6" name="new" />
    </div>

    <div class="form-group row">
        <label class="label col-sm-4"><?php _lang('confirm-new-password')?></label>
        <input type="password" class="form-control col-sm-6" name="confirm" />
    </div>

    <hr/>

    <div  style="padding: 10px; text-align: center">
        <button class="btn btn-primary btn-sm"><?php _lang('change-password')?></button>
    </div>
</form>