<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="pane">
            <div class="m-3"><h5>
                    <?php echo (segment(1) == 'followers') ? lang('followers') : lang('following')?>
            </h5></div>

            <?php $users = (segment(1) == 'followers') ? get_followers(app()->profileId) : get_following(app()->profileId); foreach($users as $user):?>
                <?php echo view('main::user/display-inline', array('user' => $user))?>
            <?php endforeach?>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>