<div class="loader-container">
    <div class="css-loader"></div>
    <p><?php _lang('please-wait')?></p>
</div>
<div class="load-bar">
    <div class="bar"></div>
    <div class="bar"></div>
    <div class="bar"></div>
</div>
<div id="post-viewer">
    <div class="cover"></div>
    <a href="" class="close"><i class="icons icon-close"></i></a>
    <div class="content container"></div>
</div>
<div id="photo-viewer">
    <div class="cover"></div>
    <a href="" class="close"><i class="icons icon-close"></i></a>
    <div class="container">
        <img src=""/>
    </div>
</div>
<div id="story-viewer">
    <a onclick="return close_story()" href="" class="close"><i class="icons icon-close"></i></a>
    <div class="content container">

    </div>
</div>
<div id="search-viewer">
    <a href="" onclick="return hide_search()" class="close"><i class="icons icon-close"></i></a>
    <div class="head">
        <div class="container">
            <div class="row">
                <div class="col-sm-10">
                    <input onkeyup="return do_search(this)" placeholder="<?php _lang('search-placeholder')?>" type="text" class="form-control"/>
                </div>
                <div class="col-sm-2">
                    <i class="icons icon-magnifier"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="container content">

    </div>
</div>
<div class="modal fade" id="reportModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php _lang('report')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <textarea class="form-control" required="required" name="" placeholder="<?php _lang('report-reason')?>"></textarea>
            </div>
            <div class="modal-footer">
                <button id="send-report-btn" type="button" class="btn btn-primary btn-sm"><?php _lang('send-report')?></button>
            </div>
        </div>
    </div>
</div>
<?php if(is_loggedin()):?>

    <div id="messagesDialog" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog ">
            <div class="modal-content"></div>
        </div>
    </div>

    <?php $badges = get_user_badges(get_userid(), true)?>
    <?php if(config('enable-badge', true) and $badges):?>
        <div class="new-badge-hover">
            <div class="cover"></div>
            <a href="" class="close" onclick="return close_new_badge()"><i class="icons icon-close"></i></a>
            <div class="container">
                <h1><?php _lang('you-have-new-badge')?></h1>
                <div style="padding: 20px 0;text-align: center">
                    <?php foreach($badges as $badge):mark_badge_seen($badge['id'])?>
                        <img class="tool-tip" style="width: 150px;margin: 10px" title="<?php echo $badge['name']?>"  src="<?php echo url($badge['image'])?>"/>
                    <?php endforeach?>
                </div>
            </div>
        </div>
        <?php endif?>

    <ul id="menu" class="mfb-component--br mfb-zoomin" data-mfb-toggle="hover">
        <li class="mfb-component__wrap">
            <a  href="#" class="mfb-component__button--main fab-button">
                <i class="mfb-component__main-icon--resting icons icon-plus"></i>
                <i class="mfb-component__main-icon--active ions icon-close"></i>
            </a>
            <ul class="mfb-component__list">
                <li>
                    <a onclick="return show_post_editor('photo')" href="" data-mfb-label="<?php _lang('add-photo')?>" class="mfb-component__button--child fab-link">
                        <i class="mfb-component__child-icon icons icon-picture"></i>
                    </a>
                </li>
                <?php if(config('enable-link-embed', true)):?>
                <li>
                    <a href="" onclick="return show_post_editor('url')" data-mfb-label="<?php _lang('embed-video-photo')?>" class="mfb-component__button--child fab-link">
                        <i class="mfb-component__child-icon icons icon-link"></i>
                    </a>
                </li>
                <?php endif?>

                <?php if(config('enable-video-upload', true)):?>
                    <li>
                        <a href="" onclick="return show_post_editor('video')"
                           data-mfb-label="<?php _lang('upload-video')?>" class="mfb-component__button--child fab-link">
                            <i class="mfb-component__child-icon icons icon-film"></i>
                        </a>
                    </li>
                <?php endif?>

                <?php if(config('enable-stories', true)):?>
                    <li>
                        <a href="" onclick="return show_post_editor('story')"
                           data-mfb-label="<?php _lang('add-story')?>" class="mfb-component__button--child fab-link">
                            <i class="mfb-component__child-icon icons icon-layers"></i>
                        </a>
                    </li>
                <?php endif?>
            </ul>
        </li>
    </ul>
    <div id="post-editor">
        <div class="cover"></div>
        <div class="container">
            <form  id="post-editor-form" action="" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-8">
                        <div class="pane" style="margin: 0">
                            <div class="head clearfix">
                                <div class="float-left">
                                    <img src="<?php echo get_avatar()?>"/>
                                    <span><?php echo get_user()['full_name']?></span>
                                </div>
                                <div class="float-right">
                                    <a href="" onclick="return hide_post_editor()" class="close"><i class="icons icon-close"></i></a>
                                </div>
                            </div>
                            <div class="body">
                                <div class=" post post-photo" style="margin-bottom: 5px">
                                    <a href="" class="hide btn btn-default btn-sm btn-block" style="margin-bottom: 5px"><?php _lang('select-a-photo')?></a>
                                    <input class="form-control" onchange="return validate_image_size(this, 'image')"  type="file" name="photo[]" multiple/>
                                </div>

                                <div class=" post post-video" style="margin-bottom: 5px">
                                    <a href="" class="btn hide btn-default btn-sm btn-block" style="margin-bottom: 5px"><?php _lang('select-a-video')?></a>
                                    <input  onchange="return validate_image_size(this, 'video')"  type="file" name="video" />
                                </div>

                                <div class=" post post-story" style="margin-bottom: 5px">
                                    <a href="" class="btn hide btn-default btn-sm btn-block" style="margin-bottom: 5px"><?php _lang('select-a-video')?></a>
                                    <input  onchange="return validate_image_size(this, 'both')"  type="file" name="story" />
                                </div>
                                <input type="text" name="url" class="form-control post post-url" style="margin-bottom: 5px" placeholder="<?php _lang('paste-a-url')?>"/>
                                <textarea placeholder="<?php _lang('add-caption')?>" class="form-control emoji-input" id="emoji-input-post" name="caption"></textarea>
                                <div class="form-group">
                                    <input style="width:100% !important;" style="margin-top: 10px" class="form-control tag-input" placeholder="<?php _lang('tags')?>" type="text" name="tag"/>
                                </div>
                            </div>
                            <div class="post-footer clearfix">
                                <button class="btn btn-sm btn-primary float-right"><?php echo strtoupper(lang('post'))?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php endif?>
<?php if(Layout::getInstance()->showHeader):?>
    <nav id="header" class="navbar  fixed-top navbar-toggleable-md navbar-light bg-faded">
        <div class="container">

            <a class="navbar-brand" href="<?php echo url()?>"><?php echo config('site-title', 'Tinsta')?></a>

            <ul class="navbar-nav mr-auto" id="header-nav">
                <?php if(is_loggedin() and has_getstarted()):?>
                    <li id="home-nav" class="nav-item <?php echo (segment(0) == '') ? 'active':null?> ">
                        <a class="nav-link ajax-link" href="<?php echo url()?>"><i class="icons icon-home"></i> <span><?php _lang('home')?></span> </a>
                    </li>
                    <li id="explore-nav" class="nav-item <?php echo (segment(0) == 'explore') ? 'active':null?>">
                        <a class="nav-link ajax-link" href="<?php echo url('explore')?>"><i class="icons icon-compass"></i> <span><?php _lang('explore')?></span></a>
                    </li>
                    <!--<li class="nav-item <?php echo (segment(0) == 'stories') ? 'active':null?>">
                        <a class="nav-link ajax-link" href="<?php echo url('stories')?>"><i class="icons icon-layers"></i> <?php _lang('stories')?></a>
                    </li>-->

                    <?php if(is_admin() or is_moderator()):?>
                        <li id="admin-nav" class="nav-item <?php echo (segment(0) == 'admin') ? 'active':null?>">
                            <a class="nav-link ajax-link" href="<?php echo url('admin')?>"><i class="icons icon-puzzle"></i> <span><?php _lang('administrator')?></span></a>
                        </li>
                    <?php endif?>
                <?php endif?>
            </ul>
            <?php if(is_loggedin() and has_getstarted()):?>
                <div class="search-control">
                    <input onfocus="return open_search()" type="text" name="search" placeholder="Search"/>
                    <i onclick="return open_search()" class="icons icon-magnifier"></i>
                </div>
            <?php endif?>

            <div class="header-right-nav">
                <ul class="navbar-nav">

                    <?php if(is_loggedin()):?>
                        <?php if(has_getstarted()):?>
                            <li class="nav-item "  style="position: relative">
                                <a style="position: relative" onclick="return open_message_dialog()" class="nav-link header-message-icon" href="#"><i class="icons icon-envelope"></i></a>
                            </li>
                            <li class="nav-item large-notification-link" style="position: relative">
                                <a class="nav-link header-notification-icon" onclick="return show_notification_dropdown()" href="#"><i class="icons icon-heart"></i></a>
                                <div class="notification-dropdown">
                                    <div class="triangle-with-shadow"></div>
                                    <div class="notification-content">
                                        <div class="notification-lists">

                                        </div>
                                        <div style="padding: 5px 10px">
                                            <a  href="<?php echo url('notifications')?>" class="ajax-link btn btn-block btn-sm btn-secondary"><?php _lang('view-all-notifications')?></a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item small-notification-link" style="position: relative">
                                <a class="ajax-link nav-link header-notification-icon"  href="<?php echo url('notifications')?>"><i class="icons icon-heart"></i></a>
                            </li>
                            <li class="nav-item user-account-menu dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"><img src="<?php echo get_avatar(75)?>"/> </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item ajax-link" href="<?php echo profile_link()?>">
                                        <h6><?php echo get_user()['full_name']?></h6>
                                        <span>@<?php echo get_user()['username']?></span>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item ajax-link" href="<?php echo profile_link()?>"><?php _lang('profile')?></a>
                                    <a class="dropdown-item ajax-link" href="<?php echo profile_link(null, 'favourites')?>"><?php _lang('favourites')?></a>
                                    <a class="dropdown-item ajax-link" href="<?php echo url('settings')?>"><?php _lang('account-settings')?></a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="<?php echo url('logout')?>"><?php _lang('logout')?></a>
                                </div>
                            </li>

                        <?php endif?>
                    <?php else:?>
                        <li class="nav-item ">
                            <a class="nav-link" href="<?php echo url('?login=true')?>"><?php _lang('login')?></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="<?php echo url('?signup=true')?>"><?php _lang('signup')?></a>
                        </li>
                    <?php endif?>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" id="main-content-area">
        <?php if(config('announcement')):?>
            <div style="margin: 5px 0" class="alert alert-<?php echo config('announcement-type', 'info')?>"><?php echo config('announcement')?> </div>
        <?php endif?>
        <div id="page-content">
            <?php echo $content;?>
        </div>

    </div>
<?php else:?>
    <?php echo $content?>
<?php endif?>
