<div id="chat-message-container">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
            <a href="" onclick="return go_back_message()"><i class="icons icon-arrow-left"></i></a>
            <?php echo $user['full_name']?>
        </h5>
        <button onclick="return close_message_dialog()" type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body" id="message-lists" data-lastcheck="<?php echo time()?>" data-offset="0" data-id="<?php echo $user['id']?>">
        <?php foreach(get_messages($user['id']) as $message):?>
            <?php  echo view('main::message/display', array('message' => $message));?>
        <?php endforeach?>
    </div>
    <form action="" method="post" class="">
        <div class="chat-message-form clearfix">
            <input type="hidden" name="to" value="<?php echo $user['id']?>"/>
            <div class="left">
                <textarea placeholder="<?php _lang('write-something')?>"  name="text" class="form-control "></textarea>
            </div>
            <div class="right">
                <div class="file-chooser">
                    <button class="btn btn-sm btn-secondary" style="margin-bottom: 2px"><i class="icons icon-picture"></i></button>
                    <input onchange="return validate_image_size(this, 'image')" type="file" name="file" multiple/>
                </div>

                <button class="btn btn-sm btn-primary"><i class="icons icon-paper-plane"></i></button>
            </div>
        </div>
    </form>
</div>