<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="pane">
            <div class="title" style="padding: 10px"><?php _lang('notifications')?></div>
            <?php $notifications = get_notifications(0, 200)?>
            <?php if(count($notifications) < 1):?>
                <div style="text-align: center;padding: 40px  10px;font-size: 15px">
                    <i class="icons icon-pie-chart" style="font-size: 50px;display: block;margin: 10px auto"></i>
                    <?php _lang('no-notifications-yet')?>
                </div>
            <?php else:?>
                <?php foreach($notifications as $notification):?>
                    <?php echo view('main::notification/display', array('notification' => $notification))?>
                <?php endforeach?>
            <?php endif?>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>