<?php if(count($notifications) < 1):?>
    <div style="text-align: center;padding: 40px  10px;font-size: 15px">
        <i class="icons icon-pie-chart" style="font-size: 50px;display: block;margin: 10px auto"></i>
        <?php _lang('no-notifications-yet')?>
    </div>
<?php else:?>
    <div style="padding-top: 10px">
        <?php foreach($notifications as $notification):?>
            <?php echo view('main::notification/display', array('notification' => $notification))?>
        <?php endforeach?>
    </div>
<?php endif?>