<div style="padding:20px 0;text-align: center">
    <h1 style="font-weight: lighter">#<?php echo $tag?></h1>

</div>

<?php $posts = get_posts(0, null, 'tag|'.$tag)?>
<?php if($posts):?>
    <div class="post-lists row post-list" data-userid="" data-page="tag|<?php echo $tag?>" data-type="grid" data-offset="0">
        <?php foreach($posts as $post):?>
            <?php echo view('main::post/each-grid', array('post' => $post));?>
        <?php endforeach?>
    </div>
<?php else:?>
    <div style="text-align: center;padding: 40px  10px;font-size: 15px">
        <i class="icons icon-pie-chart" style="font-size: 50px;display: block;margin: 10px auto"></i>
        <?php _lang('no-posts-display')?>
    </div>
<?php endif?>